BUG: Fix prerelease upload by explicitly specifying the --prerelease-sha argument
This commit fixes error like the following introduced by the previous commit:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyci/publish_github_release.py", line 597, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/anyci/publish_github_release.py", line 590, in main
    _upload_prerelease(args)
  File "/usr/local/lib/python3.9/site-packages/anyci/publish_github_release.py", line 481, in _upload_prerelease
    raise ValueError("Failed to get commit associated with --prerelease-sha: %s" % sha)
ValueError: Failed to get commit associated with --prerelease-sha: master

Exited with code exit status 1